src/DevLogs.UI/Models/ViewModels/AddUserToProject.cs
using DevLogs.Core.Entities;
using System.Collections.Generic;

namespace DevLogs.UI.Models.ViewModels
{
    public class AddUserToProject
    {
        public List<ApplicationUser> Users { get; set; }

        public int ProjectId { get; set; }
    }
}

src/DevLogs.UI/Controllers/DocumentController.cs
using ClosedXML.Excel;
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services;
using DevLogs.Core.Interfaces.Services.ProjectService;
using DevLogs.Core.Interfaces.Services.TaskService;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    public class DocumentController : Controller
    {
        private readonly IProjectService<Project> _projectService;
        private readonly IService<Document> _documentService;
        private readonly ITaskService<TaskEntity> _taskService;
        private readonly IService<SecurRole> _securRoleService;

        public DocumentController(IProjectService<Project> projectService,
            IService<Document> documentService,
             ITaskService<TaskEntity> taskService,
            IService<SecurRole> securRoleService
            )
        {
            _projectService = projectService;
            _documentService = documentService;
            _taskService = taskService;
            _securRoleService = securRoleService;
        }

        [HttpPost]
        [Route("deletedocument")]
        public async Task<IActionResult> DeleteDocument(int documentId)
        {
            var document = _documentService.GetById(documentId);
            await _documentService.Delete(document);
            return RedirectToAction("AdministrationDocumentPage", "Admin");
        }

        [HttpPost]
        [Route("createdocument")]
        public async Task<IActionResult> CreateDocument(int projectId)
        {
            var project = _projectService.GetById(projectId);

            Document document = new()
            {
                ProjectId = project.Id,
                Project = project
            };

            await _documentService.Create(document);
            return RedirectToAction("ProjectMenu", "Project", new { Id = projectId });
        }


        [HttpGet]
        [Route("projectdoc")]
        public IActionResult CreateDocReport(int projectId)
        {
            var project = _projectService.GetById(projectId);

            using (var workBook = new XLWorkbook())
            {
                var worksheet = workBook.Worksheets.Add($"Project {project.ShortName}");
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Shortname";
                worksheet.Cell(currentRow, 3).Value = "Description";
                worksheet.Cell(currentRow, 4).Value = "Time";
                worksheet.Cell(currentRow, 5).Value = "StartDate";
                worksheet.Cell(currentRow, 6).Value = "FinaleDate";
                worksheet.Cell(currentRow, 7).Value = "Status";

                currentRow++;
                worksheet.Cell(currentRow, 1).Value = project.Name;
                worksheet.Cell(currentRow, 2).Value = project.ShortName;
                worksheet.Cell(currentRow, 3).Value = project.Description;
                worksheet.Cell(currentRow, 4).Value = project.Customer;
                worksheet.Cell(currentRow, 5).Value = project.StartDate;
                worksheet.Cell(currentRow, 6).Value = project.FinaleDate;
                worksheet.Cell(currentRow, 7).Value = project.Status;

                ++currentRow;
                ++currentRow;
                worksheet.Cell(currentRow, 1).Value = "Работники";

                currentRow++;
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Surname";
                worksheet.Cell(currentRow, 3).Value = "Email";
                worksheet.Cell(currentRow, 4).Value = "Role";

                foreach(var user in project.Users)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = user.Name;
                    worksheet.Cell(currentRow, 2).Value = user.Surname;
                    worksheet.Cell(currentRow, 3).Value = user.Email;
                    worksheet.Cell(currentRow, 4).Value = _securRoleService.GetById((int)user.SecurRoleId).UserRole;
                }

                currentRow++;
                ++currentRow;
                worksheet.Cell(currentRow, 1).Value = "Задачи";

                currentRow++;

                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Description";
                worksheet.Cell(currentRow, 3).Value = "Status";
                worksheet.Cell(currentRow, 4).Value = "Time";
                worksheet.Cell(currentRow, 5).Value = "StartDate";
                worksheet.Cell(currentRow, 6).Value = "FinaleDate";

                foreach (var task in project.Tasks)
                {
                    if (task.IsOverdue == true)
                    {
                        currentRow++;
                        //worksheet.Cell(currentRow, 1).Value = task.Id;
                        worksheet.Cell(currentRow, 1).Value = task.Name;
                        worksheet.Cell(currentRow, 2).Value = task.Description;
                        worksheet.Cell(currentRow, 3).Value = task.Status;
                        worksheet.Cell(currentRow, 4).Value = task.Time;
                        worksheet.Cell(currentRow, 5).Value = task.StartDate;
                        worksheet.Cell(currentRow, 6).Value = task.FinaleDate;
                    }
                }

                using (var stream = new MemoryStream())
                {
                    workBook.SaveAs(stream);
                    var conect = stream.ToArray();
                    return File(conect, "application/vnd.openxmlformsts-officedocument.spreadsheetml.sheet", $"{project.ShortName}.xlsx");
                }
            }
        }

        [HttpGet]
        [Route("taskdoc")]
        public async Task<IActionResult> CreateTaskReport()
        {
            var tasks = await _taskService.GetAll();

            using (var workBook = new XLWorkbook())
            {
                var worksheet = workBook.Worksheets.Add("Tasks");
                var currentRow = 1;
                //worksheet.Cell(currentRow, 1).Value = "Id";
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Description";
                worksheet.Cell(currentRow, 3).Value = "Status";
                worksheet.Cell(currentRow, 4).Value = "Time";
                worksheet.Cell(currentRow, 5).Value = "StartDate";
                worksheet.Cell(currentRow, 6).Value = "FinaleDate";
                worksheet.Cell(currentRow, 7).Value = "Project";

                foreach (var task in tasks)
                {
                    if (task.IsOverdue == true)
                    {
                        currentRow++;
                        //worksheet.Cell(currentRow, 1).Value = task.Id;
                        worksheet.Cell(currentRow, 1).Value = task.Name;
                        worksheet.Cell(currentRow, 2).Value = task.Description;
                        worksheet.Cell(currentRow, 3).Value = task.Status;
                        worksheet.Cell(currentRow, 4).Value = task.Time;
                        worksheet.Cell(currentRow, 5).Value = task.StartDate;
                        worksheet.Cell(currentRow, 6).Value = task.FinaleDate;
                        worksheet.Cell(currentRow, 7).Value = task.Project.ShortName;
                    }
                }

                using (var stream = new MemoryStream())
                {
                    workBook.SaveAs(stream);
                    var conect = stream.ToArray();
                    return File(conect, "application/vnd.openxmlformsts-officedocument.spreadsheetml.sheet", "tasks.xlsx");
                }
            }
        }
    }
}

src/DevLogs.UI/Controllers/ProjectController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services;
using DevLogs.Core.Interfaces.Services.ProjectService;
using DevLogs.UI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    [Route("project")]
    //[Authorize]
    public class ProjectController : Controller
    {
        private readonly IProjectService<Project> _projectService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProjectController(IProjectService<Project> projectService, UserManager<ApplicationUser> userManager)
        {
            _projectService = projectService;
            _userManager = userManager;
        }

        [HttpGet]
        [Route("adduser")]
        public IActionResult AddUserToProject(int id)
        {
            var users = _userManager.Users.Where(u => u.Projects.All(p => p.Id != id)).ToList();

            var asignUserModel = new AddUserToProject()
            {
                Users = users,
                ProjectId = id
            };

            return View(asignUserModel);
        }

        [HttpPost]
        [Route("adduser")]
        public async Task<IActionResult> AddUserToProject(string userId, int projectId)
        {
            var user = await _userManager.FindByIdAsync(userId); ;
            var project = _projectService.GetById(projectId);
            user.Projects.Add(project);
            await _projectService.Update(project);
            return RedirectToAction("ProjectMenu", new { Id = projectId });
        }

        [HttpGet]
        [Route("projects")]
        public async Task<IActionResult> Projects(string projectName = null)
        {
            var projectList = await _projectService.GetAll();

            if (projectName != null)
            {
                var projectListWithOneElement = projectList.Where(p => (p.ShortName == projectName) || (p.Name == projectName)).ToList();

                return View(projectListWithOneElement);
            }

            return View(projectList.Where(p => p.InArchive == false).ToList());
        }

        [HttpGet]
        [Route("add")]
        public IActionResult AddProject()
        {
            if(Request.Cookies["secur-lvl"] != "Low")
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        [Route("update")]
        public IActionResult UpdateProject(int projectId)
        {
            var project = _projectService.GetById(projectId);

            return View(project);
        }

        [HttpPost]
        [Route("update")]
        public async Task<IActionResult> UpdateProject(Project viewProject)
        {
            if (viewProject.InArchive == false && viewProject.Status == "В архиве")
            {
                viewProject.InArchive = true;
            }

            if (viewProject.InArchive == true && viewProject.Status == "В разработке")
            {
                viewProject.InArchive = false;
            }

            await _projectService.Update(viewProject);

            return RedirectToAction("ProjectMenu", new { Id = viewProject.Id });
        }

        [HttpPost]
        [Route("add")]
        public async Task<IActionResult> AddProject(Project project)
        {
            if (!ModelState.IsValid)
            {
                return View(project);
            }

            await _projectService.Create(project);
            return RedirectToAction("Projects");

        }

        [HttpGet]
        [Route("{id?}")]
        public IActionResult ProjectMenu(int id)
        {
            var project = _projectService.GetById(id);
            return View(project);
        }

        [HttpGet]
        [Route("myprojects")]
        public async Task<IActionResult> MyProjects()
        {
            var userKey = Request.Cookies["user_key"];

            var user = await _userManager.Users.Include(c => c.Projects).FirstOrDefaultAsync(u => u.Id == userKey);

            return View(user.Projects.Where(p => p.InArchive == false).ToList());
        }

        [HttpGet]
        [Route("users/{id?}")]
        public IActionResult ProjectUsers(int id)
        {
            ViewBag.Id = id;

            var users = _userManager.Users.Include(u => u.Projects).ToList();//.Where(p=>p.Projects.All(p => p.Id == id && p.InArchive == false)).ToList();

            var usersPro = _projectService.GetById(id);

            return View(usersPro.Users);
        }

        [HttpPost]
        [Route("deleteuser")]
        public async Task<IActionResult> DeleteUserFromProject(int projectId, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            var project = _projectService.GetById(projectId);

            project.Users.Remove(user);

            await _projectService.Update(project);

            return RedirectToAction("ProjectUsers", new { Id = projectId });
        }
    }
}

src/DevLogs.UI/Controllers/TaskController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services.TaskService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    [Authorize]
    [Route("task")]
    public class TaskController : Controller
    {
        private readonly ITaskService<TaskEntity> _taskService;
        private readonly UserManager<ApplicationUser> _userManager;
        public TaskController(ITaskService<TaskEntity> taskService, UserManager<ApplicationUser> userManager)
        {
            _taskService = taskService;
            _userManager = userManager;
        }

        [HttpGet]
        [Route("create")]
        public IActionResult CreateNewTask(int id)
        {
            ViewBag.Id = id;

            var task = new TaskEntity()
            {
                ProjectId = id
            };
            return View(task);
        }

        [HttpGet]
        [Route("updatetask")]
        public IActionResult UpdateTask(int taskId)
        {
            var task = _taskService.GetById(taskId);
            return View(task);
        }

        [HttpPost]
        [Route("updatetask")]
        public async Task<IActionResult> UpdateTask(TaskEntity taskEntity)
        {
            var task = _taskService.GetById(taskEntity.Id);
            task.Name = taskEntity.Name;
            task.Description = taskEntity.Description;
            task.Time = taskEntity.Time;
            task.StartDate = taskEntity.StartDate;
            task.FinaleDate = taskEntity.FinaleDate;
            task.Status = taskEntity.Status;

            await _taskService.Update(task);

            return RedirectToAction("ProjectMenu", "Project", new { Id = taskEntity.ProjectId });
        }

        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> CreateTask(TaskEntity taskEntity)
        {
            if (!ModelState.IsValid)
            {
                return View(taskEntity);
            }

            taskEntity.Status = "Активно";

            await _taskService.Create(taskEntity);

            return RedirectToAction("ProjectMenu", "Project", new { Id = taskEntity.ProjectId });
        }

        [HttpGet]
        [Route("tasks")]
        public  IActionResult Tasks(int id)
        {
            ViewBag.Id = id;
            var tasks =  _taskService.GetAll().Result.Where(t=>t.ProjectId == id).ToList();
            return View(tasks);
        }

        [HttpGet]
        [Route("addusertotask")]
        public IActionResult AddUserToTask(int taskId, int projectId)
        {
            var users = _userManager.Users.Include(t => t.Tasks.Where(p=>p.Id != taskId && p.ProjectId == projectId)).ToList();

            var addUser = new AddUserToTask()
            {
                taskId = taskId,
                Users = users
            };
            return View(addUser);
        }

        [HttpPost]
        [Route("deletetask")]
        public async Task<IActionResult> DeleteTask(int taskId)
        {
            var task = _taskService.GetById(taskId);

            await _taskService.Delete(task);
            return RedirectToAction("ProjectMenu", "Project", new { Id = task.ProjectId });
        }


        [HttpPost]
        [Route("addusertotask")]
        public async Task<IActionResult> AddUserToTask(int taskId, string userId)
        {
            var task = _taskService.GetById(taskId);
            var user = await _userManager.FindByIdAsync(userId);

            task.Users.Add(user);
            await _taskService.Update(task);
            return RedirectToAction("ProjectMenu", "Project", new { Id = task.ProjectId });
        }
    }

    public class AddUserToTask
    {
        public int taskId { get; set; }

        public List<ApplicationUser> Users { get; set; }
    }
}

src/DevLogs.UI/Views/Project/AddProject.cshtml
@using DevLogs.Core.Entities
@model Project;

<div class="container">
    <h1 class="" style="text-align: center">Создать новый проект</h1>
    <form method="post" asp-action="AddProject" asp-controller="Project">
        <div>
            <div>
                <label class="lead" asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name" placeholder="Пример: Международный магазин сладостей"/>
                <span asp-validation-for="Name" />
            </div>
            <div>
                <label class="lead" asp-for="ShortName">Short name</label>
                <input class="form-control" type="text" asp-for="ShortName" placeholder="Пример: ММС"/>
                <span asp-validation-for="ShortName" />
            </div>
            <div>
                <label class="lead" asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description" placeholder="Пример: Это интернет портал для торговли разными сладостями. Пользователь должен иметь возможность сделать заказ и удобные опции для создания заказа"/>
                <span asp-validation-for="Description" />
            </div>
            <div>
                <label class="lead" asp-for="Customer">Заказчик</label>
                <input class="form-control" type="text" asp-for="Customer" placeholder="Пример: M&Ms"/>
                <span asp-validation-for="Customer" />
            </div>
            <div>
                <label class="lead" asp-for="StartDate">Дата начала</label>
                <input class="form-control" type="text" asp-for="StartDate" placeholder="Пример: 31.12.2002"/>
                <span asp-validation-for="StartDate" />
            </div>
            <div>
                <label class="lead" asp-for="FinaleDate">Дата окончания</label>
                <input class="form-control" type="text" asp-for="FinaleDate" placeholder="Пример: 31.01.2022"/>
                <span asp-validation-for="FinaleDate" />
            </div>
        </div>
        <div>
            <p></p>
            <input class="btn btn-outline-info" type="submit" value="Создать"/>
        </div>
    </form>
</div>

src/DevLogs.UI/Views/Project/AddUserToProject.cshtml
@using DevLogs.UI.Models.ViewModels
@model AddUserToProject;

<h1 style="text-align: center">Добавить пользователя на проект</h1>

<form method="post" asp-action="AddUserToProject" asp-controller="Project">
    <div>
        <select name="userId" class="custom-select">
            @foreach (var user in Model.Users)
            {
                <option value="@user.Id">
                    @user.UserName
                </option>
            }
        </select>
        <input type="hidden" name="projectId" value="@Model.ProjectId" />
    </div>
    <p></p>
    <div>
        <input type="submit" value="Добавить" class="btn btn-outline-info" />
    </div>
</form>

src/DevLogs.UI/Views/Project/MyProjects.cshtml
@using DevLogs.Core.Entities
@model List<Project>

<div class="container text-center" style="display: block; margin-left: auto; margin-right: auto;">
    <form method="get" class="input-group mb-3" style="margin-left:auto;margin-right:0">
        <input class="form-control" name="projectName" type="search" placeholder="Поиск проекта...">
        <input type="submit" class="btn btn-outline-info" />
    </form>
    <h1 style="text-align: center">Мои проекты</h1>

        @foreach (var project in Model)
        {
            <div class="custom-control-inline" style="padding-top:5px;">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <div>
                            <h5 class="card-title">@project.ShortName</h5>
                        </div>
                        <form method="get" asp-action="ProjectMenu" asp-controller="Project">
                            <input type="hidden" name="@nameof(project.Id)" value="@project.Id" />
                            <input class="btn btn-outline-info" type="submit" value="Меню проекта">
                        </form>
                    </div>
                </div>
            </div>
        }
    <div class="container" style="padding-top:200px">
        <form method="get" asp-action="AddProject" asp-controller="Project">
            Не видете нужный проект? Вы можете <strong><a asp-area="" asp-action="AddProject" asp-controller="Project">отправить сообщение</a></strong> администратору.
            Вы можете <strong><a asp-area="" asp-action="AddProject" asp-controller="Project">создать новый проект</a></strong>, если ваша роль "Проектный менеджер".
        </form>
    </div>
</div>

src/DevLogs.UI/Views/Project/ProjectMenu.cshtml
@using DevLogs.Core.Entities
@model Project

<div class="container">
    <h1 class="text-center">@Model.ShortName</h1>
    <div>
        <div class="custom-control-inline">
            <form method="get" asp-action="Tasks" asp-controller="Task">
                <input type="hidden" name="id" value="@Model.Id" />
                <input class="btn btn-outline-info" type="submit" value="Задания" />
            </form>
            @if(Context.Request.Cookies["secur-lvl"] != "Low")
            {
            <form method="get" asp-action="AddUserToProject" asp-controller="Project">
                <input type="hidden" name="id" value="@Model.Id" />
                <input class="btn btn-outline-info" type="submit" value="Добавить работника" />
            </form>
            }
            <form method="get" asp-action="ProjectUsers" asp-controller="Project">
                <input type="hidden" name="id" value="@Model.Id" />
                <input class="btn btn-outline-info" type="submit" value="Работники" />
            </form>
            @if(Context.Request.Cookies["secur-lvl"] != "Low")
            {
            <form method="get" asp-action="CreateDocReport" asp-controller="Document">
                <input type="hidden" name="projectId" value="@Model.Id" />
                <input class="btn btn-outline-info" type="submit" value="Отчет" />
            </form>
            }
        </div>
        <div>
            <label class="lead custom-control-inline"><strong>Название:</strong></label><p class="text-xl-left custom-control-inline"> @Model.Name</p>
        </div>
        <div>
            <label class="lead"><strong>Описание:</strong> </label><p class="text-xl-left"> @Model.Description</p>
        </div>
    </div>
</div>

src/DevLogs.UI/Views/Project/ProjectUsers.cshtml
@using DevLogs.Core.Entities
@model List<ApplicationUser>

<div class="container">
    <h1 style="text-align: center">Работники</h1>
    <p></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Кодовое имя
                </th>
                <th>
                    Почта
                </th>
                <th>
                    Обновление
                </th>
            </tr>
        </thead>
        @foreach (var user in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @user.UserName
                    </td>
                    <td>
                        @user.Email
                    </td>
                    <td>
                        @if (Context.Request.Cookies["secur-lvl"] != "Low")
                        {
                            <form method="post" asp-action="DeleteUserFromProject" asp-controller="Project">
                                <input type="hidden" name="userId" value="@user.Id" />
                                <input type="hidden" name="projectId" value="@ViewBag.Id" />
                                <input class="btn btn-outline-danger" type="submit" value="Снять с проекта" />
                            </form>
                        }
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Project/Projects.cshtml
@using DevLogs.Core.Entities
@model List<Project>

<div class="container text-center" style="display: block; margin-left: auto; margin-right: auto;">
    <form method="get" class="input-group mb-3" style="margin-left:auto;margin-right:0">
        <input class="form-control" name="projectName" type="search" placeholder="Поиск проекта...">
        <input type="submit" class="btn btn-outline-info" />
    </form>
    <h1 style="text-align: center">Проекты</h1>

        @foreach (var project in Model)
        {
            <div class="custom-control-inline" style="padding-top:5px;">
                <div class="card" style="width: 18rem;">
                    <div class="card-body" >
                        <div>
                            <h5 class="card-title">@project.ShortName</h5>
                        </div>
                        <form method="get" asp-action="ProjectMenu" asp-controller="Project">
                            <input type="hidden" name="@nameof(project.Id)" value="@project.Id" />
                            <input class="btn btn-outline-info" type="submit" value="Меню проекта">
                        </form>
                    </div>
                </div>
            </div>
        }
    <div class="container" style="padding-top:200px">
        <form method="get" asp-action="AddProject" asp-controller="Project">
            Не видете нужный проект? Вы можете обратиться с этим вопрос к администратору или 
            вы можете <strong><a asp-area="" asp-action="AddProject" asp-controller="Project">создать новый проект</a></strong>, если ваша роль "Проектный менеджер".
        </form>
    </div>
</div>

src/DevLogs.UI/Views/Project/UpdateProject.cshtml
@using DevLogs.Core.Entities
@model Project;

<div class="container">
    <form method="post" asp-action="UpdateProject" asp-controller="Project">
        <div>
            <div>
                <label class="lead" asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name" value="@Model.Name" placeholder="Пример: Международный магазин сладостей" />
                <span asp-validation-for="Name" />
            </div>
            <div>
                <label class="lead" asp-for="ShortName">Short name</label>
                <input class="form-control" type="text" asp-for="ShortName" value="@Model.ShortName" placeholder="Пример: ММС" />
                <span asp-validation-for="ShortName" />
            </div>
            <div>
                <label class="lead" asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description" value="@Model.Description" placeholder="Пример: Это интернет портал для торговли разными сладостями. Пользователь должен иметь возможность сделать заказ и удобные опции для создания заказа" />
                <span asp-validation-for="Description" />
            </div>
            <div>
                <label class="lead" asp-for="Customer">Заказчик</label>
                <input class="form-control" type="text" asp-for="Customer" value="@Model.Customer" placeholder="Пример: M&Ms" />
                <span asp-validation-for="Customer" />
            </div>
            <div>
                <label class="lead" asp-for="Status">Статус</label>
                <select asp-for="Status" class="custom-select">
                    <option value="В разработке">
                        В разработке
                    </option>
                    <option value="В архиве">
                        В архиве
                    </option>
                </select>
            </div>
            <div>
                <label class="lead" asp-for="StartDate">Дата начала</label>
                <input class="form-control" type="text" asp-for="ShortName" value="@Model.ShortName" placeholder="Пример: 31.12.2002" />
                <span asp-validation-for="StartDate" />
            </div>
            <div>
                <label class="lead" asp-for="FinaleDate">Дата окончания</label>
                <input class="form-control" type="text" asp-for="FinaleDate" value="@Model.FinaleDate" placeholder="Пример: 31.01.2022" />
                <span asp-validation-for="FinaleDate" />
            </div>
        </div>
        <div>
            <p></p>
            <input type="hidden" name="@nameof(Model.Id)" value="@Model.Id" />
            <input type="hidden" name="@nameof(Model.InArchive)" value="@Model.InArchive" />
            <input type="hidden" name="@nameof(Model.IsOverdue)" value="@Model.IsOverdue" />
            <input class="btn btn-outline-info" type="submit" />
        </div>
    </form>
</div>