src/DevLogs.UI/Models/UpdateUser.cs
using DevLogs.Core.Entities;
using System.Collections.Generic;

namespace DevLogs.UI.Models
{
    public class UpdateUser
    {
        public ApplicationUser User { get; set; }

        public List<SecurRole> Role { get; set; }
    }
}

src/DevLogs.UI/Controllers/AdminController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services;
using DevLogs.Core.Interfaces.Services.ProjectService;
using DevLogs.Core.Interfaces.Services.TaskService;
using DevLogs.UI.Models;
using DevLogs.UI.Models.Admin;
using DevLogs.UI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    //[Authorize]
    [Route("admin")]
    public class AdminController : Controller
    {
        private readonly IProjectService<Project> _projectService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IService<SecurRole> _securRoleService;
        private readonly IService<Document> _documentService;
        private readonly ITaskService<TaskEntity> _taskService;

        public AdminController(IProjectService<Project> projectService, UserManager<ApplicationUser> userManager, IService<SecurRole> securRoleService, IService<Document> documentService, ITaskService<TaskEntity> taskService)
        {
            _projectService = projectService;
            _userManager = userManager;
            _securRoleService = securRoleService;
            _documentService = documentService;
            _taskService = taskService;
        }

        #region Roles
        [HttpGet]
        [Route("addrole")]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [Route("addrole")]
        public async Task<IActionResult> AddRole(RoleViewModel roleViewModel)
        {
            var newRole = new SecurRole()
            {
                UserRole = roleViewModel.UserRole,
                SecurLevel = roleViewModel.SecurLevel
            };

            await _securRoleService.Create(newRole);
            return RedirectToAction("AdministrationRolesPage");
        }

        [HttpGet]
        [Route("adminrolepage")]
        public async Task<IActionResult> AdministrationRolesPage()
        {
            var roles = await _securRoleService.GetAll();

            return View(roles);
        }

        [HttpGet]
        [Route("updaterole")]
        public async Task<IActionResult> UpdateRole(int id)
        {
            var roles = await _securRoleService.GetAll();

            var role = roles.FirstOrDefault(r => r.Id == id);

            var viewRole = new RoleViewModel
            {
                Id = role.Id,
                UserRole = role.UserRole,
                SecurLevel = role.SecurLevel
            };

            return View(viewRole);
        }

        [HttpPost]
        [Route("updaterole")]
        public async Task<IActionResult> UpdateRole(RoleViewModel roleViewModel)
        {
            var role = new SecurRole()
            {
                Id = roleViewModel.Id,
                UserRole = roleViewModel.UserRole,
                SecurLevel = roleViewModel.SecurLevel
            };

            await _securRoleService.Update(role);
            return RedirectToAction("AdministrationRolesPage");
        }

        [HttpPost]
        [Route("deleterole")]
        public async Task<IActionResult> DeleteRole(int id)
        {
            var roles = await _securRoleService.GetAll();
            var role = roles.FirstOrDefault(r => r.Id == id);
            await _securRoleService.Delete(role);
            return RedirectToAction("AdministrationRolesPage");
        }
        #endregion Roles

        #region Documents

        [HttpGet]
        [Route("admindocuments")]
        public async Task<IActionResult> AdministrationDocumentPage()
        {
            var documents = await _documentService.GetAll();

            foreach (var doc in documents)
            {
                doc.Project = _projectService.GetById(doc.ProjectId);
            }

            return View(documents);
        }

        #endregion Documents

        #region Projects

        [HttpGet]
        [Route("adminproject")]
        public async Task<IActionResult> AdministrationProjectPage()
        {
            var pages = await _projectService.GetAll();

            return View(pages);
        }

        [HttpPost]
        [Route("deleteproject")]
        public async Task<IActionResult> DeleteProject(int id)
        {
            var project = _projectService.GetById(id);
            await _projectService.Delete(project);
            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpGet]
        [Route("archive")]
        public IActionResult Archive()
        {
            var projects = _projectService.GetArchive();

            return View(projects);
        }

        [HttpGet]
        [Route("updateproject")]
        public IActionResult UpdateProjectAdmin(int projectId)
        {
            var project = _projectService.GetById(projectId);

            return View(project);
        }

        [HttpPost]
        [Route("updateproject")]
        public async Task<IActionResult> UpdateProjectAdmin(Project viewProject)
        {
            if (viewProject.InArchive == false && viewProject.Status == "В архиве")
            {
                viewProject.InArchive = true;
            }

            if (viewProject.InArchive == true && viewProject.Status == "В разработке")
            {
                viewProject.InArchive = false;
            }

            await _projectService.Update(viewProject);

            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpPost]
        [Route("deletefromarchive")]
        public async Task<IActionResult> DeleteFromArchive(int id)
        {
            var project = _projectService.GetById(id);
            project.InArchive = false;
            await _projectService.Update(project);
            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpGet]
        [Route("projects/warning")]
        public async Task<IActionResult> WarningProjects()
        {
            var projects = await _projectService.GetAll();
            List<Project> list = new List<Project>();
            foreach (var project in projects)
            {
                if ((Convert.ToDateTime(project.FinaleDate) - Convert.ToDateTime(project.StartDate)).Days <= 10)
                {
                    list.Add(project);
                }
            }

            return View(list);
        }
        #endregion Projects

        #region Users
        [HttpGet]
        [Route("users")]
        public IActionResult AdministrationUsersPage()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }


        [HttpGet]
        [Route("updateuser")]
        public async Task<IActionResult> UpdateUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            var updateModel = new UpdateUser()
            {
                User = user,
                Role = await _securRoleService.GetAll()
            };

            return View(updateModel);
        }

        [HttpPost]
        [Route("updateuser")]
        public async Task<IActionResult> UpdateUser(UpdateUser updateUser,string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            user.Name = updateUser.User.Name;
            user.Surname = updateUser.User.Surname;
            user.UserName = updateUser.User.UserName;
            user.SecurRoleId = updateUser.User.SecurRoleId;
            user.SecurRole = _securRoleService.GetById((int)updateUser.User.SecurRoleId);
            user.Email = updateUser.User.Email;

            await _userManager.UpdateAsync(user);

            return RedirectToAction("AdministrationUsersPage");
        }

        [HttpPost]
        [Route("deleteuser")]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("AdministrationUsersPage");
        }

        [HttpGet]
        public IActionResult RecoveryPasswordFromAdmin(string userId)
        {
            var recoveryPasswordModel = new RecoveryPasswordFromAdmin()
            {
                UserId = userId
            };

            return View(recoveryPasswordModel);
        }

        [HttpPost]
        public async Task<IActionResult> RecoveryPasswordFromAdmin(RecoveryPasswordFromAdmin recoveryPasswordFromAdmin)
        {
            var user = await _userManager.FindByIdAsync(recoveryPasswordFromAdmin.UserId);
            await _userManager.RemovePasswordAsync(user);
            await _userManager.AddPasswordAsync(user, recoveryPasswordFromAdmin.NewPassword);
            return View();
        }
        #endregion Users

        [HttpGet]
        [Route("tasks")]
        public async Task<IActionResult> AdministrationTasksPage()
        {
            var users = await _taskService.GetAll();
            return View(users);
        }

        [HttpGet]
        [Route("addusertotask")]
        public IActionResult AddUserToTask(int taskId)
        {
            var task = _taskService.GetById(taskId);
            var users = _userManager.Users.Include(t => t.Tasks.Where(p => p.Id != taskId && p.ProjectId == task.ProjectId)).ToList();

            var addUser = new AddUserToTask()
            {
                taskId = taskId,
                Users = users
            };
            return View(addUser);
        }

        [HttpPost]
        [Route("addusertotask")]
        public async Task<IActionResult> AddUserToTask(int taskId, string userId)
        {
            var task = _taskService.GetById(taskId);
            var user = await _userManager.FindByIdAsync(userId);

            task.Users.Add(user);
            await _taskService.Update(task);

src/DevLogs.UI/Controllers/AuthController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces;
using DevLogs.Core.Interfaces.Services;
using DevLogs.UI.Models;
using DevLogs.UI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    [Route("auth")]
    [AllowAnonymous]
    public class AuthController : Controller
    {
        #region Fields
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly IEmailService _emailService;
        private readonly IService<SecurRole> _securRoleService;

        #endregion Fields

        public AuthController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailService emailService,
            IService<SecurRole> securRoleService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailService = emailService;
            _securRoleService = securRoleService;
        }

        #region Register
        [HttpGet]
        [Route("register")]
        public async Task<IActionResult> Register()
        {
            var registerUser = new RegisterUser();
            var roles = await _securRoleService.GetAll();
            registerUser.Roles = roles.Select(r => new RoleViewModel()
            {
                Id = r.Id,
                UserRole = r.UserRole
            }).ToList();

            return View(registerUser);
        }

        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register(RegisterUser registerUser)
        {
            if (!ModelState.IsValid)
            {
                return View(registerUser);
            }

            ApplicationUser user = new()
            {
                Name = registerUser.Name,
                Surname = registerUser.Surname,
                UserName = registerUser.CodeName,
                Email = registerUser.Email,
                SecurRoleId = registerUser.RoleId,
                SecurRole = _securRoleService.GetById(registerUser.RoleId)
            };

            var result = await _userManager.CreateAsync(user, registerUser.Password);

            if (!result.Succeeded)
            {
                return View(registerUser);
            }

            await _emailService.SendEmailAsync(user.Email, "You creditionals", "Login: " + user.Email + " Password: " + registerUser.Password + "\n Your role is" + user.SecurRole.UserRole);

            return RedirectToAction("Index", "Home");
        }
        #endregion Register

        #region Login/Logout
        [HttpGet]
        [Route("login")]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [Route("login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(RegisterUser userModel)
        {
            if (!ModelState.IsValid)
            {
                return View(userModel);
            }

            var user = await _userManager.FindByEmailAsync(userModel.Email);

            var result = await _userManager.CheckPasswordAsync(user, userModel.Password);

            if (!result)
            {
                return View(userModel);
            }

            await _signInManager.SignInAsync(user, false);
            Response.Cookies.Append("user_key", user.Id);
            Response.Cookies.Append("user_name_varificate", user.UserName);
            Response.Cookies.Append("secur-lvl", _securRoleService.GetById((int)user.SecurRoleId).SecurLevel);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("logout")]
        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            Response.Cookies.Delete("user_name_varificate");
            Response.Cookies.Delete("user_key");
            Response.Cookies.Delete("secur-lvl");
            return RedirectToAction("LogIn");
        }
        #endregion Login/logout

        [HttpGet]
        [Route("recoverypassword")]
        public IActionResult RecoveryPassword(ApplicationUser user)
        {
            return View(user);
        }

        [HttpPost]
        [Route("recoverypassword")]
        public async Task<IActionResult> RecoveryPassword(string id, string oldPassword, string oldPasswordConfim, string newPassword)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (oldPassword != oldPasswordConfim)
            {
                return View(user);
            }

            var resalt = await _signInManager.CheckPasswordSignInAsync(user, oldPassword, false);

            if (!resalt.Succeeded)
            {
                return View(user);
            }

            await _userManager.ChangePasswordAsync(user, oldPassword, newPassword);

            return View();
        }

        [HttpGet]
        [Route("users")]
        public IActionResult Users(string email = null)
        {
            var users = _userManager.Users.ToList();

            if (email != null)
            {
                return View(users.Where(u => u.Email == email).ToList());
            }

            return View(users);
        }

        [HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            return View(user);
        }

        [HttpGet]
        [Route("myaccount")]
        public async Task<IActionResult> MyAccount()
        {
            var userKey = Request.Cookies["user_key"];

            if (userKey == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var user = await _userManager.Users.Include(c => c.Projects).Include(c => c.Tasks).Include(r => r.SecurRole).FirstOrDefaultAsync(u => u.Id == userKey);

            return View(user);
        }
    }
}

src/DevLogs.UI/Views/Admin/AddRole.cshtml
@using DevLogs.Core.Entities
@model SecurRole

<h1 style="text-align: center">Добавить новую роль</h1>
<form method="post" asp-action="AddRole" asp-controller="Admin">
    <div>
        <div>
            <label class="lead" asp-for="UserRole">Роль пользователя: </label>
            <input class="form-control" type="text" asp-for="UserRole" placeholder="Пример: Middle .NET Developer"/>
            <span asp-validation-for="UserRole"/>
        </div>
        <div>
            <label class="lead" asp-for="UserRole">Роль пользователя: </label>
            <select asp-for="SecurLevel" class="custom-select">
                <option>Low</option>
                <option>Middle</option>
                <option>High</option>
                <option>Special</option>
            </select>
        </div>
    </div>
    <div>
        <p></p>
        <input class="btn btn-outline-info" type="submit" value="Добавить"/>
    </div>
</form>

src/DevLogs.UI/Views/Admin/AddUserToTask.cshtml
@using DevLogs.UI.Controllers
@model AddUserToTask

<h1 style="text-align: center">Назначить пользователя на задачу</h1>

<form method="post" asp-action="AddUserToTask" asp-controller="Admin">
    <div>
        <select name="userId" class="custom-select">
            @foreach (var user in Model.Users)
            {
                <option value="@user.Id">
                    @user.UserName
                </option>
            }
        </select>
    </div>
    <p></p>
    <div>
        <input type="hidden" name="taskId" value="@Model.taskId" />
        <input type="submit" value="Добавить" class="btn btn-outline-info" />
    </div>
</form>

src/DevLogs.UI/Views/Admin/AdminUpdateTask.cshtml
@using DevLogs.Core.Entities
@model TaskEntity

<div>
    <h1 style="text-align: center">Обновить задачу</h1>

    <form method="post" asp-action="AdminUpdateTask" asp-controller="Admin">
        <div>
            <div>
                <label class="lead" asp-for="Name">Название</label>
                <input class="form-control" type="text" asp-for="Name" autocomplete="off" placeholder="GCS-123 Create models for query to database" />
                <span asp-validation-for="Name" />
            </div>
            <div>
                <label class="lead" asp-for="Description">Описание</label>
                <input class="form-control" type="text" asp-for="Description" autocomplete="off" placeholder="Create new model in 'Entities' folder" />
                <span asp-validation-for="Description" />
            </div>
            <div>
                <label class="lead" asp-for="Time">Время на выполнение задачи в часах</label>
                <input class="form-control" type="text" asp-for="Time" autocomplete="off" placeholder="8" />
                <span asp-validation-for="Time" />
            </div>
            <div>
                <label class="lead" asp-for="Status">Статус: </label>
                <select asp-for="Status" class="custom-select">
                    <option value="Активно">
                        Активна
                    </option>
                    <option value="Закончена">
                        Закончена
                    </option>
                </select>
            </div>
            <div>
                <label class="lead" asp-for="StartDate">Дата начала</label>
                <input class="form-control" type="text" asp-for="StartDate" autocomplete="off" placeholder="01.01.2022" />
                <span asp-validation-for="StartDate" />
            </div>
            <div>
                <label class="lead" asp-for="FinaleDate">Дата конца</label>
                <input class="form-control" type="text" asp-for="FinaleDate" autocomplete="off" placeholder="02.01.2022" />
                <span asp-validation-for="FinaleDate" />
            </div>
        </div>
        <div>
            <p></p>
            <input type="hidden" name="@nameof(Model.Id)" value="@Model.Id" />
            <input type="hidden" name="@nameof(Model.ProjectId) value="@Model.ProjectId />
            <input class="btn btn-outline-info" type="submit" />
        </div>
    </form>
</div>

src/DevLogs.UI/Views/Admin/AdministrationProjectPage.cshtml
@using DevLogs.Core.Entities
@model List<Project>

    <h1 style="text-align: center">Администрирование проектов</h1>
<div class="container">
    <div class="custom-control-inline">
        <form method="get" asp-action="AddProject" asp-controller="Project">
            <input class="btn btn-outline-info" type="submit" value="Создать" />
        </form>
        <form method="get" asp-action="Archive" asp-controller="Admin">
            <input class="btn btn-outline-info" type="submit" value="Архив" />
        </form>
    </div>
    <p></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Название
                </th>
                <th>
                    Заказчик
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Обновление
                </th>
                <th>
                    Удаление
                </th>
            </tr>
        </thead>
        @foreach (var project in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @project.ShortName
                    </td>
                    <td>
                        @project.Customer
                    </td>
                    <td>
                        @project.Description
                    </td>
                    <td>
                        <form method="get" asp-action="UpdateProjectAdmin" asp-controller="Admin">
                            <input type="hidden" name="projectId" value="@project.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteProject" asp-controller="Admin">
                            <input type="hidden" name="id" value="@project.Id" />
                            <input class="btn btn-outline-danger" type="submit" value="Удалить" />
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Admin/AdministrationRolesPage.cshtml
@using DevLogs.Core.Entities
@model List<SecurRole>

    <h1 style="text-align: center">Администрирование ролей</h1>
<div class="container">
    <div class="custom-control-inline">
        <form method="get" asp-action="AddRole" asp-controller="Admin">
            <input class="btn btn-outline-info" type="submit" value="Создать" />
        </form>
    </div>
    <p></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Роль
                </th>
                <th>
                    Уровень доступа
                </th>
                <th>
                    Обновление
                </th>
                <th>
                    Удаление
                </th>
            </tr>
        </thead>
        @foreach (var role in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @role.UserRole
                    </td>
                    <td>
                        @role.SecurLevel
                    </td>
                    <td>
                        <form method="get" asp-action="UpdateRole" asp-controller="Admin">
                            <input type="hidden" name="id" value="@role.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteRole" asp-controller="Admin">
                            <input type="hidden" name="id" value="@role.Id" />
                            <input class="btn btn-outline-danger" type="submit" value="Удалить" />
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Admin/AdministrationTasksPage.cshtml
@using DevLogs.Core.Entities
@model List<TaskEntity>


<h1 style="text-align: center">Администрирование задач</h1>
<form method="get" asp-action="CreateTaskReport" asp-controller="Document">
    <input class="btn btn-outline-info" type="submit" value="Отчет о просроченных задачах"/>
</form>
<div style="padding-top:35px">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Название
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Обновить
                </th>
                <th>
                    Готово
                </th>
                <th scope="col">
                    Работники
                </th>
            </tr>
        </thead>
        @foreach (var task in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @task.Name
                    </td>
                    <td>
                        @task.Description
                    </td>
                    <td>
                        <form method="get" asp-action="AdminUpdateTask" asp-controller="Admin">
                            <input type="hidden" name="taskId" value="@task.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteTask" asp-controller="Admin">
                            <input type="hidden" name="taskId" value="@task.Id" />
                            <input class="btn btn-outline-info" type="submit" value="Закрыть" />
                        </form>
                    </td>
                    <td>
                        <form method="get" asp-action="AddUserToTask" asp-controller="Admin">
                            <input type="hidden" name="taskId" value="@task.Id" />
                            <input type="hidden" name="projectId" value="@ViewBag.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Назначить" />
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Admin/AdministrationUsersPage.cshtml
@using DevLogs.Core.Entities
@model List<ApplicationUser>

<div class="container">
    <h1 style="text-align: center">Администрирование пользователей</h1>
    <div class="custom-control-inline" style="padding-top: 35px">
        <form method="get" asp-action="Register" asp-controller="Auth">
            <input class="btn btn-outline-info" type="submit" value="Создать нового пользователя" />
        </form>
    </div>
    <p></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Кодовое имя
                </th>
                <th>
                    Почта
                </th>
                <th>
                    Обновление
                </th>
                <th>
                    Удаление
                </th>
            </tr>
        </thead>
        @foreach (var user in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @user.UserName
                    </td>
                    <td>
                        @user.Email
                    </td>
                    <td>
                        <form method="get" asp-action="UpdateUser" asp-controller="Admin">
                            <input type="hidden" name="userId" value="@user.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteUser" asp-controller="Admin">
                            <input type="hidden" name="userId" value="@user.Id" />
                            <input class="btn btn-outline-danger" type="submit" value="Удалить" />
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Admin/Archive.cshtml
@using DevLogs.Core.Entities
@model List<Project>

<h1 style="text-align: center"> Архив</h1>
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Название
                </th>
                <th>
                    Заказчик
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Обновление
                </th>
                <th>
                    Разархивация
                </th>
                <th>
                    Удаление
                </th>
            </tr>
        </thead>
        @foreach (var project in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @project.ShortName
                    </td>
                    <td>
                        @project.Customer
                    </td>
                    <td>
                        @project.Description
                    </td>
                    <td>
                        <form method="get" asp-action="UpdateProjectAdmin" asp-controller="Admin">
                            <input type="hidden" name="projectId" value="@project.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteFromArchive" asp-controller="Admin">
                            <input type="hidden" name="id" value="@project.Id" />
                            <input class="btn btn-outline-warning" type="submit" value="Разархивировать" />
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-action="DeleteProject" asp-controller="Admin">
                            <input type="hidden" name="id" value="@project.Id" />
                            <input class="btn btn-outline-danger" type="submit" value="Удалить" />
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>