src/DevLogs.UI/Models/ViewModels/TaskViewModel.cs
using System;
using System.Collections.Generic;

namespace DevLogs.UI.Models.ViewModels
{
    public class TaskViewModel
    {
        public TaskViewModel()
        {
            Users = new List<UserViewModel>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Status { get; set; }

        public int Time { get; set; }

        public string Start { get; set; }

        public string FinaleDate { get; set; }

        public int ProjectId { get; set; }

        public string ProjectShortName { get; set; }

        public List<UserViewModel> Users { get; set; }
    }
}

src/DevLogs.UI/Controllers/AdminController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services;
using DevLogs.Core.Interfaces.Services.ProjectService;
using DevLogs.Core.Interfaces.Services.TaskService;
using DevLogs.UI.Models;
using DevLogs.UI.Models.Admin;
using DevLogs.UI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    //[Authorize]
    [Route("admin")]
    public class AdminController : Controller
    {
        private readonly IProjectService<Project> _projectService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IService<SecurRole> _securRoleService;
        private readonly IService<Document> _documentService;
        private readonly ITaskService<TaskEntity> _taskService;

        public AdminController(IProjectService<Project> projectService, UserManager<ApplicationUser> userManager, IService<SecurRole> securRoleService, IService<Document> documentService, ITaskService<TaskEntity> taskService)
        {
            _projectService = projectService;
            _userManager = userManager;
            _securRoleService = securRoleService;
            _documentService = documentService;
            _taskService = taskService;
        }

        #region Roles
        [HttpGet]
        [Route("addrole")]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [Route("addrole")]
        public async Task<IActionResult> AddRole(RoleViewModel roleViewModel)
        {
            var newRole = new SecurRole()
            {
                UserRole = roleViewModel.UserRole,
                SecurLevel = roleViewModel.SecurLevel
            };

            await _securRoleService.Create(newRole);
            return RedirectToAction("AdministrationRolesPage");
        }

        [HttpGet]
        [Route("adminrolepage")]
        public async Task<IActionResult> AdministrationRolesPage()
        {
            var roles = await _securRoleService.GetAll();

            return View(roles);
        }

        [HttpGet]
        [Route("updaterole")]
        public async Task<IActionResult> UpdateRole(int id)
        {
            var roles = await _securRoleService.GetAll();

            var role = roles.FirstOrDefault(r => r.Id == id);

            var viewRole = new RoleViewModel
            {
                Id = role.Id,
                UserRole = role.UserRole,
                SecurLevel = role.SecurLevel
            };

            return View(viewRole);
        }

        [HttpPost]
        [Route("updaterole")]
        public async Task<IActionResult> UpdateRole(RoleViewModel roleViewModel)
        {
            var role = new SecurRole()
            {
                Id = roleViewModel.Id,
                UserRole = roleViewModel.UserRole,
                SecurLevel = roleViewModel.SecurLevel
            };

            await _securRoleService.Update(role);
            return RedirectToAction("AdministrationRolesPage");
        }

        [HttpPost]
        [Route("deleterole")]
        public async Task<IActionResult> DeleteRole(int id)
        {
            var roles = await _securRoleService.GetAll();
            var role = roles.FirstOrDefault(r => r.Id == id);
            await _securRoleService.Delete(role);
            return RedirectToAction("AdministrationRolesPage");
        }
        #endregion Roles

        #region Documents

        [HttpGet]
        [Route("admindocuments")]
        public async Task<IActionResult> AdministrationDocumentPage()
        {
            var documents = await _documentService.GetAll();

            foreach (var doc in documents)
            {
                doc.Project = _projectService.GetById(doc.ProjectId);
            }

            return View(documents);
        }

        #endregion Documents

        #region Projects

        [HttpGet]
        [Route("adminproject")]
        public async Task<IActionResult> AdministrationProjectPage()
        {
            var pages = await _projectService.GetAll();

            return View(pages);
        }

        [HttpPost]
        [Route("deleteproject")]
        public async Task<IActionResult> DeleteProject(int id)
        {
            var project = _projectService.GetById(id);
            await _projectService.Delete(project);
            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpGet]
        [Route("archive")]
        public IActionResult Archive()
        {
            var projects = _projectService.GetArchive();

            return View(projects);
        }

        [HttpGet]
        [Route("updateproject")]
        public IActionResult UpdateProjectAdmin(int projectId)
        {
            var project = _projectService.GetById(projectId);

            return View(project);
        }

        [HttpPost]
        [Route("updateproject")]
        public async Task<IActionResult> UpdateProjectAdmin(Project viewProject)
        {
            if (viewProject.InArchive == false && viewProject.Status == "В архиве")
            {
                viewProject.InArchive = true;
            }

            if (viewProject.InArchive == true && viewProject.Status == "В разработке")
            {
                viewProject.InArchive = false;
            }

            await _projectService.Update(viewProject);

            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpPost]
        [Route("deletefromarchive")]
        public async Task<IActionResult> DeleteFromArchive(int id)
        {
            var project = _projectService.GetById(id);
            project.InArchive = false;
            await _projectService.Update(project);
            return RedirectToAction("AdministrationProjectPage");
        }

        [HttpGet]
        [Route("projects/warning")]
        public async Task<IActionResult> WarningProjects()
        {
            var projects = await _projectService.GetAll();
            List<Project> list = new List<Project>();
            foreach (var project in projects)
            {
                if ((Convert.ToDateTime(project.FinaleDate) - Convert.ToDateTime(project.StartDate)).Days <= 10)
                {
                    list.Add(project);
                }
            }

            return View(list);
        }
        #endregion Projects

        #region Users
        [HttpGet]
        [Route("users")]
        public IActionResult AdministrationUsersPage()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }


        [HttpGet]
        [Route("updateuser")]
        public async Task<IActionResult> UpdateUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            var updateModel = new UpdateUser()
            {
                User = user,
                Role = await _securRoleService.GetAll()
            };

            return View(updateModel);
        }

        [HttpPost]
        [Route("updateuser")]
        public async Task<IActionResult> UpdateUser(UpdateUser updateUser,string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            user.Name = updateUser.User.Name;
            user.Surname = updateUser.User.Surname;
            user.UserName = updateUser.User.UserName;
            user.SecurRoleId = updateUser.User.SecurRoleId;
            user.SecurRole = _securRoleService.GetById((int)updateUser.User.SecurRoleId);
            user.Email = updateUser.User.Email;

            await _userManager.UpdateAsync(user);

            return RedirectToAction("AdministrationUsersPage");
        }

        [HttpPost]
        [Route("deleteuser")]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("AdministrationUsersPage");
        }

        [HttpGet]
        public IActionResult RecoveryPasswordFromAdmin(string userId)
        {
            var recoveryPasswordModel = new RecoveryPasswordFromAdmin()
            {
                UserId = userId
            };

            return View(recoveryPasswordModel);
        }

        [HttpPost]
        public async Task<IActionResult> RecoveryPasswordFromAdmin(RecoveryPasswordFromAdmin recoveryPasswordFromAdmin)
        {
            var user = await _userManager.FindByIdAsync(recoveryPasswordFromAdmin.UserId);
            await _userManager.RemovePasswordAsync(user);
            await _userManager.AddPasswordAsync(user, recoveryPasswordFromAdmin.NewPassword);
            return View();
        }
        #endregion Users

        [HttpGet]
        [Route("tasks")]
        public async Task<IActionResult> AdministrationTasksPage()
        {
            var users = await _taskService.GetAll();
            return View(users);
        }

        [HttpGet]
        [Route("addusertotask")]
        public IActionResult AddUserToTask(int taskId)
        {
            var task = _taskService.GetById(taskId);
            var users = _userManager.Users.Include(t => t.Tasks.Where(p => p.Id != taskId && p.ProjectId == task.ProjectId)).ToList();

            var addUser = new AddUserToTask()
            {
                taskId = taskId,
                Users = users
            };
            return View(addUser);
        }

        [HttpPost]
        [Route("addusertotask")]
        public async Task<IActionResult> AddUserToTask(int taskId, string userId)
        {
            var task = _taskService.GetById(taskId);
            var user = await _userManager.FindByIdAsync(userId);

            task.Users.Add(user);
            await _taskService.Update(task);

src/DevLogs.UI/Controllers/TaskController.cs
using DevLogs.Core.Entities;
using DevLogs.Core.Interfaces.Services.TaskService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevLogs.UI.Controllers
{
    [Authorize]
    [Route("task")]
    public class TaskController : Controller
    {
        private readonly ITaskService<TaskEntity> _taskService;
        private readonly UserManager<ApplicationUser> _userManager;
        public TaskController(ITaskService<TaskEntity> taskService, UserManager<ApplicationUser> userManager)
        {
            _taskService = taskService;
            _userManager = userManager;
        }

        [HttpGet]
        [Route("create")]
        public IActionResult CreateNewTask(int id)
        {
            ViewBag.Id = id;

            var task = new TaskEntity()
            {
                ProjectId = id
            };
            return View(task);
        }

        [HttpGet]
        [Route("updatetask")]
        public IActionResult UpdateTask(int taskId)
        {
            var task = _taskService.GetById(taskId);
            return View(task);
        }

        [HttpPost]
        [Route("updatetask")]
        public async Task<IActionResult> UpdateTask(TaskEntity taskEntity)
        {
            var task = _taskService.GetById(taskEntity.Id);
            task.Name = taskEntity.Name;
            task.Description = taskEntity.Description;
            task.Time = taskEntity.Time;
            task.StartDate = taskEntity.StartDate;
            task.FinaleDate = taskEntity.FinaleDate;
            task.Status = taskEntity.Status;

            await _taskService.Update(task);

            return RedirectToAction("ProjectMenu", "Project", new { Id = taskEntity.ProjectId });
        }

        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> CreateTask(TaskEntity taskEntity)
        {
            if (!ModelState.IsValid)
            {
                return View(taskEntity);
            }

            taskEntity.Status = "Активно";

            await _taskService.Create(taskEntity);

            return RedirectToAction("ProjectMenu", "Project", new { Id = taskEntity.ProjectId });
        }

        [HttpGet]
        [Route("tasks")]
        public  IActionResult Tasks(int id)
        {
            ViewBag.Id = id;
            var tasks =  _taskService.GetAll().Result.Where(t=>t.ProjectId == id).ToList();
            return View(tasks);
        }

        [HttpGet]
        [Route("addusertotask")]
        public IActionResult AddUserToTask(int taskId, int projectId)
        {
            var users = _userManager.Users.Include(t => t.Tasks.Where(p=>p.Id != taskId && p.ProjectId == projectId)).ToList();

            var addUser = new AddUserToTask()
            {
                taskId = taskId,
                Users = users
            };
            return View(addUser);
        }

        [HttpPost]
        [Route("deletetask")]
        public async Task<IActionResult> DeleteTask(int taskId)
        {
            var task = _taskService.GetById(taskId);

            await _taskService.Delete(task);
            return RedirectToAction("ProjectMenu", "Project", new { Id = task.ProjectId });
        }


        [HttpPost]
        [Route("addusertotask")]
        public async Task<IActionResult> AddUserToTask(int taskId, string userId)
        {
            var task = _taskService.GetById(taskId);
            var user = await _userManager.FindByIdAsync(userId);

            task.Users.Add(user);
            await _taskService.Update(task);
            return RedirectToAction("ProjectMenu", "Project", new { Id = task.ProjectId });
        }
    }

    public class AddUserToTask
    {
        public int taskId { get; set; }

        public List<ApplicationUser> Users { get; set; }
    }
}

src/DevLogs.UI/Views/Task/AddUserToTask.cshtml
@using DevLogs.UI.Controllers
@model AddUserToTask

<h1 style="text-align: center">Назначить пользователя на задачу</h1>

<form method="post" asp-action="AddUserToTask" asp-controller="Task">
    <div>
        <select name="userId" class="custom-select">
            @foreach (var user in Model.Users)
            {
                <option value="@user.Id">
                    @user.UserName
                </option>
            }
        </select>
        
    </div>
    <p></p>
    <div>
        <input type="hidden" name="taskId" value="@Model.taskId" />
        <input type="submit" value="Добавить" class="btn btn-outline-info" />
    </div>
</form>

src/DevLogs.UI/Views/Task/CreateNewTask.cshtml
@using DevLogs.Core.Entities
@model TaskEntity

<div>
    <h1 style="text-align: center">Создать задачу</h1>

    <form method="post" asp-action="CreateTask" asp-controller="Task">
        <div>
            <div>
                <label class="lead" asp-for="Name">Название</label>
                <input class="form-control" type="text" asp-for="Name" autocomplete="off" placeholder="GCS-123 Create models for query to database"/>
                <span asp-validation-for="Name" />
            </div>
            <div>
                <label class="lead" asp-for="Description">Описание</label>
                <input class="form-control" type="text" asp-for="Description" autocomplete="off" placeholder="Create new model in 'Entities' folder"/>
                <span asp-validation-for="Description"/>
            </div>
            <div>
                <label class="lead" asp-for="Time">Время на выполнение задачи в часах</label>
                <input class="form-control" type="text" asp-for="Time" autocomplete="off" placeholder="8"/>
                <span asp-validation-for="Time" />
            </div>
            <div>
                <label class="lead" asp-for="StartDate">Время начала</label>
                <input class="form-control" type="text" asp-for="StartDate" autocomplete="off" placeholder="01.01.2022"/>
                <span asp-validation-for="StartDate"/>
            </div>
            <div>
                <label class="lead" asp-for="FinaleDate">Время окончания</label>
                <input class="form-control" type="text" asp-for="FinaleDate" autocomplete="off" placeholder="02.01.2022"/>
                <span asp-validation-for="FinaleDate" />
            </div>
        </div>
        <div>
            <p></p>
            <input type="hidden" name="@nameof(Model.ProjectId)" value="@ViewBag.Id"/>
            <input class="btn btn-outline-info" type="submit" />
        </div>
    </form>
</div>

src/DevLogs.UI/Views/Task/Tasks.cshtml
@using DevLogs.Core.Entities
@model List<TaskEntity>

<div class="container">
    <h1 style="text-align: center">Задачи</h1>
    @if (Context.Request.Cookies["secur-lvl"] != "Low")
    {
        <form method="get" asp-action="CreateNewTask" asp-controller="Task">
            <input type="hidden" name="id" value="@ViewBag.Id" />
            <input class="btn btn-outline-warning" type="submit" value="Создать" />
        </form>
        <p></p>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Название
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Обновить
                </th>
                <th>
                    Готово
                </th>
                <th scope="col">
                    Работники
                </th>
            </tr>
        </thead>
        @foreach (var task in Model)
        {
            <tbody>
                <tr>
                    <td>
                        @task.Name
                    </td>
                    <td>
                        @task.Description
                    </td>
                    <td>
                        @if (Context.Request.Cookies["secur-lvl"] != "Low")
                        {
                            <form method="get" asp-action="UpdateTask" asp-controller="Task">
                                <input type="hidden" name="taskId" value="@task.Id" />
                                <input class="btn btn-outline-warning" type="submit" value="Обновить" />
                            </form>
                        }
                    </td>
                    <td>
                        @if (Context.Request.Cookies["secur-lvl"] != "Low")
                        {
                            <form method="post" asp-action="DeleteTask" asp-controller="Task">
                                <input type="hidden" name="taskId" value="@task.Id" />
                                <input class="btn btn-outline-info" type="submit" value="Закрыть" />
                            </form>
                        }
                    </td>
                    <td>
                        @if (Context.Request.Cookies["secur-lvl"] != "Low")
                        {
                            <form method="get" asp-action="AddUserToTask" asp-controller="Admin">
                                <input type="hidden" name="taskId" value="@task.Id" />
                                <input type="hidden" name="projectId" value="@ViewBag.Id" />
                                <input class="btn btn-outline-warning" type="submit" value="Назначить" />
                            </form>
                        }
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

src/DevLogs.UI/Views/Task/UpdateTask.cshtml
@using DevLogs.Core.Entities
@model TaskEntity

<div>
    <h1 style="text-align: center">Обновить задачу</h1>

    <form method="post" asp-action="UpdateTask" asp-controller="Task">
        <div>
            <div>
                <label class="lead" asp-for="Name">Название</label>
                <input class="form-control" type="text" asp-for="Name" autocomplete="off" placeholder="GCS-123 Create models for query to database" />
                <span asp-validation-for="Name" />
            </div>
            <div>
                <label class="lead" asp-for="Description">Описание</label>
                <input class="form-control" type="text" asp-for="Description" autocomplete="off" placeholder="Create new model in 'Entities' folder" />
                <span asp-validation-for="Description" />
            </div>
            <div>
                <label class="lead" asp-for="Time">Время на выполнение задачи в часах</label>
                <input class="form-control" type="text" asp-for="Time" autocomplete="off" placeholder="8" />
                <span asp-validation-for="Time" />
            </div>
            <div>
                <label class="lead" asp-for="Status">Статус: </label>
                <select asp-for="Status" class="custom-select">
                    <option value="Активно">
                        Активна
                    </option>
                    <option value="Закончена">
                        Закончена
                    </option>
                </select>
            </div>
            <div>
                <label class="lead" asp-for="StartDate">Дата начала</label>
                <input class="form-control" type="text" asp-for="StartDate" autocomplete="off" placeholder="01.01.2022" />
                <span asp-validation-for="StartDate" />
            </div>
            <div>
                <label class="lead" asp-for="FinaleDate">Дата окончания</label>
                <input class="form-control" type="text" asp-for="FinaleDate" autocomplete="off" placeholder="02.01.2022" />
                <span asp-validation-for="FinaleDate" />
            </div>
        </div>
        <div>
            <p></p>
            <input type="hidden" name="@nameof(Model.Id)" value="@Model.Id" />
            <input type="hidden" name="@nameof(Model.ProjectId)" value="@Model.ProjectId" />
            <input class="btn btn-outline-info" type="submit" />
        </div>
    </form>
</div>